name: Tests and code analysis
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [['3.9', 'py39']]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version[0] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version[0] }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test ${{ matrix.python-version[1] }} with tox
        run: tox -e ${{ matrix.python-version[1] }}